#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DEVICE=dream

mkdir -p ../../../vendor/htc/$DEVICE

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g > ../../../vendor/htc/$DEVICE/device_$DEVICE-vendor.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Live wallpaper packages
PRODUCT_PACKAGES := \\
    Superuser 

# make more enterprisey
PRODUCT_PROPERTY_OVERRIDES += \\
    keyguard.no_require_sim=true \\
    ro.com.android.dataroaming=false \\
    ro.com.google.clientidbase=android-google \\
    ro.config.alarm_alert=Alarm_Classic.ogg \\
    ro.config.notification_sound=pixiedust.ogg \\
    ro.config.ringtone=Ring_Digital_02.ogg \\
    ro.config.sync=yes \\
    ro.media.dec.aud.wma.enabled=1 \\
    ro.media.dec.vid.wmv.enabled=1 \\
    ro.modversion=distilled-0.200 \\
    ro.rommanager.developerid=avatar \\
    ro.setupwizard.enterprise_mode=1 \\
    ro.setupwizard.mode=OPTIONAL

# protected apps market hack
PRODUCT_BUILD_PROP_OVERRIDES += \\
    BUILD_ID=FRF91 \\
    BUILD_DISPLAY_ID=FRF91 \\
    BUILD_VERSION_TAGS="ota-rel-keys,test-keys" \\
    BUILD_FINGERPRINT="google/passion/passion/mahimahi:2.2/FRF91/43546:user/release-keys" \\
    PRIVATE_BUILD_DESC="passion-user 2.2 FRF91 43546 release-keys"

# This file is generated by device/htc/__DEVICE__/setup-makefiles.sh

\$(call inherit-product, vendor/htc/__DEVICE__/device___DEVICE__-vendor-blobs.mk)
EOF

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g > ../../../vendor/htc/$DEVICE/BoardConfigVendor.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/__DEVICE__/setup-makefiles.sh

BOARD_GPS_LIBRARIES := libgps

USE_CAMERA_STUB := false
EOF
